[package]
name = "trade-lang-core"
version = "0.1.0"
edition = "2024"

[dependencies]
trade-meta-compiler = { git = "https://github.com/miaomiaowu0428/trade-meta-compiler.git" }
# trade-meta-compiler = { path = "../trade-meta-compiler" }
parking_lot = "0.12"
log = "0.4"
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
ahash = "0.8"
